version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./back/students
    ports:
      - "8082:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/student_db
      DATABASE_USERNAME: student
      DATABASE_PASSWORD: student
    depends_on:
      - database

  frontend:
    build:
      context: ./front
      args:
        BACKEND_API_URL: http://localhost:8082/api
    ports:
      - "82:80"
    depends_on:
      - backend

volumes:
  postgres_data: